# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcbc22946f8c49f2c51a80d752b8cf6f9f04082b782dd39edfc388e137fa16910c1c3179f8d2a98df433facb9f98de53cab1569323852eefdc1c2ba5b3ec65a1

test:
  secret_key_base: 62c8f483b53010de0676a23e19993a7ce3271bbaf9f7396343b51c472dcc2d6c16453cb3a3ae01d2549f2066606475170764d3d12303ee6cc552dcd99de02e14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
